### ISSUE TITLE
[Feature] - Response 필드명 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#116]
## ✏️Description
- 모든 응답 필드명 수정하기

## ✅TODO
- [x] 기업 응답 수정하기
- [x] 문의 응답 수정하기
- [x] 회원 응답 수정하기
- [x] 질문 응답 수정하기
- [x] 답변 응답 수정하기
- [x] 신고 응답 수정하기
