### ISSUE TITLE
[Feature] - 리팩토링하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#118]
## ✏️Description
- 네이버 개발자 선생님이 주신 코드 리뷰대로 전면 리팩토링 진행하기

## ✅TODO
- [x] 인덱스 개념 찾아보고 검색 쿼리에서 인덱스 생성하기
- [x] 논리적으로만 삭제한 데이터들을 스케쥴링을 통해 주기적으로 지우기
- [x] 비슷한 기능들을 따로 메서드 분리하기
- [x] @Positive 애노테이션 알아보고 적용하기
- [x] Validation 애노테이션 알아보고 사용하기
- [x] 생성 로직은 객체에서 하도록 수정하기
- [x] 깃허브 액션 파일 분리해서 트리거 기준 다르게 잡기
- [x] 트랜잭션 애노테이션 전부 메서드 단위에서 적용하기
- [x] for문들 스트림 적용하기
- [x] NotNull 보장 파라미터들의 타입을 원시 타입으로 수정하기
- [x] PAGE_SIZE를 상수로 수정하기
- [x] 모든 상태들 enum으로 수정하기
- [x] update 목적에 맞게 API 분리하기
- [x] value 전부 지우기
- [x] 응답 메시지 지우기
- [x] 응답 코드 목적에 맞게 세분화하기
- [x] 예외 클래스에서 Object 타입으로 전면 수정하기
- [x] 쿼리문 멀티라인 스트링으로 수정하기
- [x] DB엔 영어가 들어가도록하고 자바에서 한글 주석을 달기
- [x] REST API의 Path는 최대한 명사로 구성하기
- [x] 동작 (find, delete) 등은 REST API의 Method로 판단하도록 매핑 애노테이션 수정하기
- [x] final 파라미터 단에서만 사용하기
