### ISSUE TITLE
[Feature] - [CI/CD] 운영 환경 배포

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#13]
## ✏️Description
- 운영 환경 배포

## ✅TODO
- [x] AWS EC2/RDS 운영 환경 생성하기
- [x] 가비아 도메인 구매하기
- [x] AWS Route 53 도메인 등록하기
- [x] EC2 인스턴스에 Spring Boot 운영 환경 배포하기
- [x] Nginx 설정하기
- [x] Certbot으로 Let's Encrypt 인증서 받기
