### ISSUE TITLE
[Feature] - [Inquiry] 내 문의 개수 조회 API 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#133]
## ✏️Description
- 내 문의 조회 시 전체, 답변완료, 답변대기 개수 응답 API 추가하기

## ✅TODO
- [x] 전체 개수 카운트
- [x] 답변완료 개수 카운트
- [x] 답변대기 개수 카운트
