### ISSUE TITLE
[Feature] - [Question] 질문 엔티티에 태그, 카테고리 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#149]
## ✏️Description
- 질문 엔티티에 태그, 카테고리 추가하기

## ✅TODO
- [x] 태그 enum 생성하기
- [x] 카테고리 enum 생성하기
- [x] 질문 엔티티에 태그, 카테고리 추가하기
