### ISSUE TITLE
[Feature] - [Member] 회원가입 시 추가 정보 등록 API 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#26]
## ✏️Description
- 회원가입 시 소셜 로그인 후 추가 정보 등록하는 기능 구현하기

## ✅TODO
- [x] 닉네임/태그/연령대/성별 등록하기
- [x] Null은 default로 등록하기
  - [x] 닉네임 디폴트: 회원의 이메일 값
  - [x] 태그 디폴트: 취준
  - [x] 연령대/성별 디폴트: Null
