### ISSUE TITLE
[Feature] - [CI/CD] CI/CD 구축하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#3]
## ✏️Description
- CI/CD 구축
- 우선 프론트에서 원활한 API 사용을 위해 개발 환경만 배포
- GitHub Actions, AWS, Docker 등 사용

## ✅TODO
- [x] AWS EC2 dev 인스턴스 생성하기
- [x] AWS RDS dev DB 생성하기
- [x] application.yml 파일 생성하기
- [x] dev 인스턴스에 도커 설치하기
- [x] 깃허브 액션 워크플로우 파일 수정하기

## 🐾ETC
