### ISSUE TITLE
[Feature] - [Company] 회사 CUD 기능 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#66]
## ✏️Description
- 회사 CUD 기능 구현합니다.

## ✅TODO
- [x] 회사 등록 API 구현하기
- [x] 회사 수정 API 구현하기
- [x] 회사 삭제 API 구현하기
