### ISSUE TITLE
[Feature] - 특정 행동 시 붕어빵 획득/차감 기능 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#74]
## ✏️Description
- 출석 체크, 질문 작성, 답변 작성 시 붕어빵 획득/차감 기능 구현하기

## ✅TODO
- [x] 출석 체크 시 붕어빵 획득 기능 구현하기
- [x] 질문 작성 시 붕어빵 차감 기능 구현하기
- [x] 답변 작성 시 붕어빵 획득 기능 구현하기
