### ISSUE TITLE
[Feature] - [Question] 질문 시 붕어빵 걸기, 채택 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [COFLLL/CoverFlow-BE#86]
## ✏️Description
- 출첵 시 5개 증가
- 질문 시 기본 10개 차감, 채택 시 지급할 붕어빵 개수 설정
- 채택 기능 구현하기

## ✅TODO
- [x] 출첵 기존 30개에서 5개로 수정하기
- [x] 질문 시 기본 10개 차감 기능 구현하기
- [x] 채택자에게 줄 붕어빵 거는 기능 구현하기
- [x] 채택 기능 구현하기
